# Generated by Django 6.0.1 on 2026-01-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('workflows', '0002_document_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Earned', 'Earned Leave'), ('Maternity', 'Maternity Leave'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.employee'),
        ),
    ]
