# Generated by Django 6.0.1 on 2026-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('driver', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('students_assigned', models.ManyToManyField(blank=True, to='core.student')),
            ],
        ),
    ]
